In [6]:
import torch

In [7]:
x = torch.empty(4, 4)

print("Array Type: {}".format(x.type)) # type
print("Array Shape: {}".format(x.shape)) # shape
print(x)

Array Type: <built-in method type of Tensor object at 0x119cba990>
Array Shape: torch.Size([4, 4])
tensor([[ 0.0000e+00, -2.0000e+00,  4.3129e-12, -2.8643e-42],
        [ 4.7339e+30,  2.9514e+29,  1.4607e-19,  1.8888e+31],
        [ 3.1035e+27,  3.3460e-12,  1.4583e-19,  1.8888e+31],
        [ 4.9656e+28,  7.9463e+08,  5.0944e-14,  3.6734e-40]])


In [8]:
random_tensor = torch.rand(5, 4)
print(random_tensor)

tensor([[0.2828, 0.2428, 0.5132, 0.7704],
        [0.3845, 0.5860, 0.0324, 0.3021],
        [0.7384, 0.8151, 0.3306, 0.0879],
        [0.4642, 0.2409, 0.8530, 0.9072],
        [0.8574, 0.1865, 0.6609, 0.4125]])


In [16]:
import numpy as np
array = np.random.rand(4, 3)

transformed_tensor = torch.from_numpy(array)
print("{}\n".format(transformed_tensor))

tensor([[0.7222, 0.9897, 0.6118],
        [0.5643, 0.4092, 0.6259],
        [0.0015, 0.9633, 0.0429],
        [0.9125, 0.1428, 0.1724]], dtype=torch.float64)



In [17]:
numpy_arr = transformed_tensor.numpy()
print("{} {}\n".format(type(numpy_arr), numpy_arr))

<class 'numpy.ndarray'> [[0.72224268 0.98966482 0.61181629]
 [0.56429197 0.40922908 0.62586799]
 [0.00149661 0.96334083 0.04291204]
 [0.9124734  0.14282782 0.17242882]]



In [18]:
vector = torch.tensor([1, 2, 3, 4, 5, 6])
print(vector[1:4])

tensor([2, 3, 4])


In [19]:
print(vector[1:])

tensor([2, 3, 4, 5, 6])


In [21]:
float_vector = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(float_vector)

tensor([1., 2., 3., 4., 5., 6.])


In [23]:
print(float_vector.dtype)

torch.float32


In [24]:
tensor_1 = torch.tensor([2, 3, 4])
tensor_2 = torch.tensor([3, 4, 5])
tensor_1 + tensor_2

tensor([5, 7, 9])

In [25]:
tensor_1 * 5

tensor([10, 15, 20])

In [26]:
d_product = torch.dot(tensor_1, tensor_2)
d_product

tensor(38)

In [29]:
matrix = torch.tensor([1, 3, 5, 6, 8, 0]).view(2, 3)
matrix

tensor([[1, 3, 5],
        [6, 8, 0]])

In [31]:
matrix_b = torch.tensor([1, 3, 5, 6, 8, 0]).view(3, 2)
matrix_b

tensor([[1, 3],
        [5, 6],
        [8, 0]])

In [33]:
torch.matmul(matrix, matrix_b)

tensor([[56, 21],
        [46, 66]])